# Generated by Django 4.0.3 on 2023-06-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_sale_automobile_alter_sale_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='sales_rest.automobilevo'),
        ),
    ]
