# Generated by Django 4.0.3 on 2023-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_vip_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=50),
        ),
    ]
