# Generated by Django 4.0.3 on 2023-06-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_automobilevo_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
    ]
